// <copyright file="CountriesDataServiceMock.cs" company="Martialtech®">
// Solution: MartialBase.Web
// Project: MartialBase.Web.Data
// Copyright © 2020 Martialtech®. All rights reserved.
// </copyright>

using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;

using MartialBase.API.Models.DTOs.Countries;
using MartialBase.Web.Data.Services.Interfaces;
using MartialBase.Web.Data.Utilities;
using MartialBase.Web.MockData.Tools;

namespace MartialBase.Web.MockData.Services;

public class CountriesDataServiceMock : ICountriesDataService
{
    private readonly List<CountryDTO> _countries = new()
    {
        new CountryDTO { Code = "AFG", Name = "Afghanistan" },
        new CountryDTO { Code = "ALA", Name = "Åland Islands" },
        new CountryDTO { Code = "ALB", Name = "Albania" },
        new CountryDTO { Code = "DZA", Name = "Algeria" },
        new CountryDTO { Code = "ASM", Name = "American Samoa" },
        new CountryDTO { Code = "AND", Name = "Andorra" },
        new CountryDTO { Code = "AGO", Name = "Angola" },
        new CountryDTO { Code = "AIA", Name = "Anguilla" },
        new CountryDTO { Code = "ATA", Name = "Antarctica" },
        new CountryDTO { Code = "ATG", Name = "Antigua and Barbuda" },
        new CountryDTO { Code = "ARG", Name = "Argentina" },
        new CountryDTO { Code = "ARM", Name = "Armenia" },
        new CountryDTO { Code = "ABW", Name = "Aruba" },
        new CountryDTO { Code = "AUS", Name = "Australia" },
        new CountryDTO { Code = "AUT", Name = "Austria" },
        new CountryDTO { Code = "AZE", Name = "Azerbaijan" },
        new CountryDTO { Code = "BHS", Name = "The Bahamas" },
        new CountryDTO { Code = "BHR", Name = "Bahrain" },
        new CountryDTO { Code = "BGD", Name = "Bangladesh" },
        new CountryDTO { Code = "BRB", Name = "Barbados" },
        new CountryDTO { Code = "BLR", Name = "Belarus" },
        new CountryDTO { Code = "BEL", Name = "Belgium" },
        new CountryDTO { Code = "BLZ", Name = "Belize" },
        new CountryDTO { Code = "BEN", Name = "Benin" },
        new CountryDTO { Code = "BMU", Name = "Bermuda" },
        new CountryDTO { Code = "BTN", Name = "Bhutan" },
        new CountryDTO { Code = "BOL", Name = "Bolivia" },
        new CountryDTO { Code = "BIH", Name = "Bosnia and Herzegovina" },
        new CountryDTO { Code = "BWA", Name = "Botswana" },
        new CountryDTO { Code = "BRA", Name = "Brazil" },
        new CountryDTO { Code = "BRN", Name = "Brunei" },
        new CountryDTO { Code = "BGR", Name = "Bulgaria" },
        new CountryDTO { Code = "BFA", Name = "Burkina Faso" },
        new CountryDTO { Code = "BDI", Name = "Burundi" },
        new CountryDTO { Code = "CPV", Name = "Cabo Verde" },
        new CountryDTO { Code = "KHM", Name = "Cambodia" },
        new CountryDTO { Code = "CMR", Name = "Cameroon" },
        new CountryDTO { Code = "CAN", Name = "Canada" },
        new CountryDTO { Code = "CYM", Name = "Cayman Islands" },
        new CountryDTO { Code = "CAF", Name = "Central African Republic" },
        new CountryDTO { Code = "TCD", Name = "Chad" },
        new CountryDTO { Code = "CHL", Name = "Chile" },
        new CountryDTO { Code = "CHN", Name = "China" },
        new CountryDTO { Code = "CXR", Name = "Christmas Island" },
        new CountryDTO { Code = "CCK", Name = "The Cocos (Keeling) Islands" },
        new CountryDTO { Code = "COL", Name = "Colombia" },
        new CountryDTO { Code = "COM", Name = "Comoros" },
        new CountryDTO { Code = "COD", Name = "Democratic Republic of the Congo" },
        new CountryDTO { Code = "COG", Name = "The Congo" },
        new CountryDTO { Code = "COK", Name = "Cook Islands" },
        new CountryDTO { Code = "CRI", Name = "Costa Rica" },
        new CountryDTO { Code = "CIV", Name = "Côte d'Ivoire" },
        new CountryDTO { Code = "HRV", Name = "Croatia" },
        new CountryDTO { Code = "CUB", Name = "Cuba" },
        new CountryDTO { Code = "CUW", Name = "Curaçao" },
        new CountryDTO { Code = "CYP", Name = "Cyprus" },
        new CountryDTO { Code = "CZE", Name = "Czech Republic" },
        new CountryDTO { Code = "DNK", Name = "Denmark" },
        new CountryDTO { Code = "DJI", Name = "Djibouti" },
        new CountryDTO { Code = "DMA", Name = "Dominica" },
        new CountryDTO { Code = "ECU", Name = "Ecuador" },
        new CountryDTO { Code = "EGY", Name = "Egypt" },
        new CountryDTO { Code = "SLV", Name = "El Salvador" },
        new CountryDTO { Code = "GNQ", Name = "Equatorial Guinea" },
        new CountryDTO { Code = "ERI", Name = "Eritrea" },
        new CountryDTO { Code = "EST", Name = "Estonia" },
        new CountryDTO { Code = "SWZ", Name = "Eswatini" },
        new CountryDTO { Code = "ETH", Name = "Ethiopia" },
        new CountryDTO { Code = "FLK", Name = "Falkland Islands" },
        new CountryDTO { Code = "FRO", Name = "Faroe Islands" },
        new CountryDTO { Code = "FJI", Name = "Fiji" },
        new CountryDTO { Code = "FIN", Name = "Finland" },
        new CountryDTO { Code = "FRA", Name = "France" },
        new CountryDTO { Code = "GUF", Name = "French Guiana" },
        new CountryDTO { Code = "PYF", Name = "French Polynesia" },
        new CountryDTO { Code = "GAB", Name = "Gabon" },
        new CountryDTO { Code = "GMB", Name = "Gambia" },
        new CountryDTO { Code = "GEO", Name = "Georgia" },
        new CountryDTO { Code = "DEU", Name = "Germany" },
        new CountryDTO { Code = "GHA", Name = "Ghana" },
        new CountryDTO { Code = "GIB", Name = "Gibraltar" },
        new CountryDTO { Code = "GRC", Name = "Greece" },
        new CountryDTO { Code = "GRL", Name = "Greenland" },
        new CountryDTO { Code = "GRD", Name = "Grenada" },
        new CountryDTO { Code = "GLP", Name = "Guadeloupe" },
        new CountryDTO { Code = "GUM", Name = "Guam" },
        new CountryDTO { Code = "GTM", Name = "Guatemala" },
        new CountryDTO { Code = "GGY", Name = "Guernsey" },
        new CountryDTO { Code = "GIN", Name = "Guinea" },
        new CountryDTO { Code = "GNB", Name = "Guinea-Bissau" },
        new CountryDTO { Code = "GUY", Name = "Guyana" },
        new CountryDTO { Code = "HTI", Name = "Haiti" },
        new CountryDTO { Code = "VAT", Name = "Holy See" },
        new CountryDTO { Code = "HND", Name = "Honduras" },
        new CountryDTO { Code = "HKG", Name = "Hong Kong" },
        new CountryDTO { Code = "HUN", Name = "Hungary" },
        new CountryDTO { Code = "ISL", Name = "Iceland" },
        new CountryDTO { Code = "IND", Name = "India" },
        new CountryDTO { Code = "IDN", Name = "Indonesia" },
        new CountryDTO { Code = "IRN", Name = "Iran" },
        new CountryDTO { Code = "IRQ", Name = "Iraq" },
        new CountryDTO { Code = "IRL", Name = "Ireland" },
        new CountryDTO { Code = "IMN", Name = "Isle of Man" },
        new CountryDTO { Code = "ISR", Name = "Israel" },
        new CountryDTO { Code = "ITA", Name = "Italy" },
        new CountryDTO { Code = "JAM", Name = "Jamaica" },
        new CountryDTO { Code = "JPN", Name = "Japan" },
        new CountryDTO { Code = "JEY", Name = "Jersey" },
        new CountryDTO { Code = "JOR", Name = "Jordan" },
        new CountryDTO { Code = "KAZ", Name = "Kazakhstan" },
        new CountryDTO { Code = "KEN", Name = "Kenya" },
        new CountryDTO { Code = "KIR", Name = "Kiribati" },
        new CountryDTO { Code = "PRK", Name = "North Korea" },
        new CountryDTO { Code = "KOR", Name = "South Korea" },
        new CountryDTO { Code = "KWT", Name = "Kuwait" },
        new CountryDTO { Code = "KGZ", Name = "Kyrgyzstan" },
        new CountryDTO { Code = "LVA", Name = "Latvia" },
        new CountryDTO { Code = "LBN", Name = "Lebanon" },
        new CountryDTO { Code = "LSO", Name = "Lesotho" },
        new CountryDTO { Code = "LBR", Name = "Liberia" },
        new CountryDTO { Code = "LBY", Name = "Libya" },
        new CountryDTO { Code = "LIE", Name = "Liechtenstein" },
        new CountryDTO { Code = "LTU", Name = "Lithuania" },
        new CountryDTO { Code = "LUX", Name = "Luxembourg" },
        new CountryDTO { Code = "MAC", Name = "Macao" },
        new CountryDTO { Code = "MKD", Name = "North Macedonia" },
        new CountryDTO { Code = "MDG", Name = "Madagascar" },
        new CountryDTO { Code = "MWI", Name = "Malawi" },
        new CountryDTO { Code = "MYS", Name = "Malaysia" },
        new CountryDTO { Code = "MDV", Name = "Maldives" },
        new CountryDTO { Code = "MLI", Name = "Mali" },
        new CountryDTO { Code = "MLT", Name = "Malta" },
        new CountryDTO { Code = "MHL", Name = "Marshall Islands" },
        new CountryDTO { Code = "MTQ", Name = "Martinique" },
        new CountryDTO { Code = "MRT", Name = "Mauritania" },
        new CountryDTO { Code = "MUS", Name = "Mauritius" },
        new CountryDTO { Code = "MYT", Name = "Mayotte" },
        new CountryDTO { Code = "MEX", Name = "Mexico" },
        new CountryDTO { Code = "FSM", Name = "Micronesia" },
        new CountryDTO { Code = "MDA", Name = "Moldova" },
        new CountryDTO { Code = "MCO", Name = "Monaco" },
        new CountryDTO { Code = "MNG", Name = "Mongolia" },
        new CountryDTO { Code = "MNE", Name = "Montenegro" },
        new CountryDTO { Code = "MSR", Name = "Montserrat" },
        new CountryDTO { Code = "MAR", Name = "Morocco" },
        new CountryDTO { Code = "MOZ", Name = "Mozambique" },
        new CountryDTO { Code = "MMR", Name = "Myanmar" },
        new CountryDTO { Code = "NAM", Name = "Namibia" },
        new CountryDTO { Code = "NRU", Name = "Nauru" },
        new CountryDTO { Code = "NPL", Name = "Nepal" },
        new CountryDTO { Code = "NLD", Name = "Netherlands" },
        new CountryDTO { Code = "NCL", Name = "New Caledonia" },
        new CountryDTO { Code = "NZL", Name = "New Zealand" },
        new CountryDTO { Code = "NIC", Name = "Nicaragua" },
        new CountryDTO { Code = "NER", Name = "Niger" },
        new CountryDTO { Code = "NGA", Name = "Nigeria" },
        new CountryDTO { Code = "NIU", Name = "Niue" },
        new CountryDTO { Code = "NFK", Name = "Norfolk Island" },
        new CountryDTO { Code = "MNP", Name = "Northern Mariana Islands" },
        new CountryDTO { Code = "NOR", Name = "Norway" },
        new CountryDTO { Code = "OMN", Name = "Oman" },
        new CountryDTO { Code = "PAK", Name = "Pakistan" },
        new CountryDTO { Code = "PLW", Name = "Palau" },
        new CountryDTO { Code = "PSE", Name = "Palestine" },
        new CountryDTO { Code = "PAN", Name = "Panama" },
        new CountryDTO { Code = "PNG", Name = "Papua New Guinea" },
        new CountryDTO { Code = "PRY", Name = "Paraguay" },
        new CountryDTO { Code = "PER", Name = "Peru" },
        new CountryDTO { Code = "PHL", Name = "The Philippines" },
        new CountryDTO { Code = "PCN", Name = "Pitcairn" },
        new CountryDTO { Code = "POL", Name = "Poland" },
        new CountryDTO { Code = "PRT", Name = "Portugal" },
        new CountryDTO { Code = "PRI", Name = "Puerto Rico" },
        new CountryDTO { Code = "QAT", Name = "Qatar" },
        new CountryDTO { Code = "REU", Name = "Réunion" },
        new CountryDTO { Code = "ROU", Name = "Romania" },
        new CountryDTO { Code = "RUS", Name = "Russia" },
        new CountryDTO { Code = "RWA", Name = "Rwanda" },
        new CountryDTO { Code = "BLM", Name = "Saint Barthélemy" },
        new CountryDTO { Code = "KNA", Name = "Saint Kitts and Nevis" },
        new CountryDTO { Code = "LCA", Name = "Saint Lucia" },
        new CountryDTO { Code = "MAF", Name = "Saint Martin" },
        new CountryDTO { Code = "SPM", Name = "Saint Pierre and Miquelon" },
        new CountryDTO { Code = "VCT", Name = "St. Vincent & Grenadines" },
        new CountryDTO { Code = "WSM", Name = "Samoa" },
        new CountryDTO { Code = "SMR", Name = "San Marino" },
        new CountryDTO { Code = "STP", Name = "Sao Tome & Principe" },
        new CountryDTO { Code = "SAU", Name = "Saudi Arabia" },
        new CountryDTO { Code = "SEN", Name = "Senegal" },
        new CountryDTO { Code = "SRB", Name = "Serbia" },
        new CountryDTO { Code = "SYC", Name = "Seychelles" },
        new CountryDTO { Code = "SLE", Name = "Sierra Leone" },
        new CountryDTO { Code = "SGP", Name = "Singapore" },
        new CountryDTO { Code = "SXM", Name = "Sint Maarten" },
        new CountryDTO { Code = "SVK", Name = "Slovakia" },
        new CountryDTO { Code = "SVN", Name = "Slovenia" },
        new CountryDTO { Code = "SLB", Name = "Solomon Islands" },
        new CountryDTO { Code = "SOM", Name = "Somalia" },
        new CountryDTO { Code = "ZAF", Name = "South Africa" },
        new CountryDTO { Code = "SSD", Name = "South Sudan" },
        new CountryDTO { Code = "ESP", Name = "Spain" },
        new CountryDTO { Code = "LKA", Name = "Sri Lanka" },
        new CountryDTO { Code = "SDN", Name = "Sudan" },
        new CountryDTO { Code = "SUR", Name = "Suriname" },
        new CountryDTO { Code = "SWE", Name = "Sweden" },
        new CountryDTO { Code = "CHE", Name = "Switzerland" },
        new CountryDTO { Code = "SYR", Name = "Syria" },
        new CountryDTO { Code = "TWN", Name = "Taiwan" },
        new CountryDTO { Code = "TJK", Name = "Tajikistan" },
        new CountryDTO { Code = "TZA", Name = "Tanzania" },
        new CountryDTO { Code = "THA", Name = "Thailand" },
        new CountryDTO { Code = "TLS", Name = "Timor-Leste" },
        new CountryDTO { Code = "TGO", Name = "Togo" },
        new CountryDTO { Code = "TKL", Name = "Tokelau" },
        new CountryDTO { Code = "TON", Name = "Tonga" },
        new CountryDTO { Code = "TTO", Name = "Trinidad and Tobago" },
        new CountryDTO { Code = "TUN", Name = "Tunisia" },
        new CountryDTO { Code = "TUR", Name = "Turkey" },
        new CountryDTO { Code = "TKM", Name = "Turkmenistan" },
        new CountryDTO { Code = "TCA", Name = "Turks and Caicos Islands" },
        new CountryDTO { Code = "TUV", Name = "Tuvalu" },
        new CountryDTO { Code = "UGA", Name = "Uganda" },
        new CountryDTO { Code = "UKR", Name = "Ukraine" },
        new CountryDTO { Code = "ARE", Name = "United Arab Emirates" },
        new CountryDTO { Code = "GBR", Name = "United Kingdom" },
        new CountryDTO { Code = "UMI", Name = "United States Minor Outlying Islands" },
        new CountryDTO { Code = "USA", Name = "United States of America" },
        new CountryDTO { Code = "URY", Name = "Uruguay" },
        new CountryDTO { Code = "UZB", Name = "Uzbekistan" },
        new CountryDTO { Code = "VUT", Name = "Vanuatu" },
        new CountryDTO { Code = "VEN", Name = "Venezuela" },
        new CountryDTO { Code = "VNM", Name = "Vietnam" },
        new CountryDTO { Code = "VGB", Name = "British Virgin Islands" },
        new CountryDTO { Code = "VIR", Name = "U.S. Virgin Islands" },
        new CountryDTO { Code = "WLF", Name = "Wallis & Futuna" },
        new CountryDTO { Code = "ESH", Name = "Western Sahara" },
        new CountryDTO { Code = "YEM", Name = "Yemen" },
        new CountryDTO { Code = "ZMB", Name = "Zambia" },
        new CountryDTO { Code = "ZWE", Name = "Zimbabwe" }
    };

    /// <inheritdoc />
    public async Task<ApiResult<List<CountryDTO>>> GetCountries(string token)
    {
        var response = HttpResponseGenerator.GetResponseMessage(_countries);

        return await ApiResult<List<CountryDTO>>.GenerateAPIResult(response);
    }

    /// <inheritdoc />
    public async Task<ApiResult<CountryDTO>> GetCountry(string countryCode, string token)
    {
        var country = _countries.FirstOrDefault(c => c.Code == countryCode);
        var response = country != null
            ? HttpResponseGenerator.GetResponseMessage(country, HttpStatusCode.NotFound)
            : new HttpResponseMessage(HttpStatusCode.NotFound);

        return await ApiResult<CountryDTO>.GenerateAPIResult(response);
    }
}