//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MartialBase.Web.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MartialBase.Web.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Person.
        /// </summary>
        public static string AddNewPersonOption {
            get {
                return ResourceManager.GetString("AddNewPersonOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Record?.
        /// </summary>
        public static string AddNewRecordTitle {
            get {
                return ResourceManager.GetString("AddNewRecordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Person Details.
        /// </summary>
        public static string AddPersonDetailsTitle {
            get {
                return ResourceManager.GetString("AddPersonDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigning person to user....
        /// </summary>
        public static string AssigningPersonToUser {
            get {
                return ResourceManager.GetString("AssigningPersonToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Assigned Person.
        /// </summary>
        public static string ChangeAssignedPersonOption {
            get {
                return ResourceManager.GetString("ChangeAssignedPersonOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here.
        /// </summary>
        public static string ClickHere {
            get {
                return ResourceManager.GetString("ClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Lock Out.
        /// </summary>
        public static string ConfirmLockOutTitle {
            get {
                return ResourceManager.GetString("ConfirmLockOutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to create a new person record or find an existing person to assign?.
        /// </summary>
        public static string CreateNewPersonOrFindExistingPrompt {
            get {
                return ResourceManager.GetString("CreateNewPersonOrFindExistingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details for &apos;{0}&apos; updated successfully..
        /// </summary>
        public static string DetailsForPersonUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("DetailsForPersonUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Assigned Record.
        /// </summary>
        public static string EditAssignedRecordOption {
            get {
                return ResourceManager.GetString("EditAssignedRecordOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Existing Record?.
        /// </summary>
        public static string EditExistingRecordPrompt {
            get {
                return ResourceManager.GetString("EditExistingRecordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to edit the assigned person record or change the assigned person?.
        /// </summary>
        public static string EditOrChangeAssignedPersonPrompt {
            get {
                return ResourceManager.GetString("EditOrChangeAssignedPersonPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Person Details.
        /// </summary>
        public static string EditPersonDetailsTitle {
            get {
                return ResourceManager.GetString("EditPersonDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to confirm email..
        /// </summary>
        public static string EmailConfirmationFailed {
            get {
                return ResourceManager.GetString("EmailConfirmationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email confirmed! You can now log in using your credentials..
        /// </summary>
        public static string EmailConfirmationSuccessful {
            get {
                return ResourceManager.GetString("EmailConfirmationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address not confirmed..
        /// </summary>
        public static string EmailNotConfirmed {
            get {
                return ResourceManager.GetString("EmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided authentication token has expired or has been revoked..
        /// </summary>
        public static string ExpiredToken {
            get {
                return ResourceManager.GetString("ExpiredToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to assign person to user..
        /// </summary>
        public static string FailedToAssignPersonToUser {
            get {
                return ResourceManager.GetString("FailedToAssignPersonToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get invitation code for user..
        /// </summary>
        public static string FailedToGetInvitationCodeForUser {
            get {
                return ResourceManager.GetString("FailedToGetInvitationCodeForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load organisations..
        /// </summary>
        public static string FailedToLoadOrganisations {
            get {
                return ResourceManager.GetString("FailedToLoadOrganisations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load person details..
        /// </summary>
        public static string FailedToLoadPersonDetails {
            get {
                return ResourceManager.GetString("FailedToLoadPersonDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load schools..
        /// </summary>
        public static string FailedToLoadSchools {
            get {
                return ResourceManager.GetString("FailedToLoadSchools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load system roles..
        /// </summary>
        public static string FailedToLoadSystemRoles {
            get {
                return ResourceManager.GetString("FailedToLoadSystemRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load user details..
        /// </summary>
        public static string FailedToLoadUserDetails {
            get {
                return ResourceManager.GetString("FailedToLoadUserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load user roles..
        /// </summary>
        public static string FailedToLoadUserRoles {
            get {
                return ResourceManager.GetString("FailedToLoadUserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load users..
        /// </summary>
        public static string FailedToLoadUsers {
            get {
                return ResourceManager.GetString("FailedToLoadUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve current user details..
        /// </summary>
        public static string FailedToRetrieveCurrentUserDetails {
            get {
                return ResourceManager.GetString("FailedToRetrieveCurrentUserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set roles for user..
        /// </summary>
        public static string FailedToSetRolesForUser {
            get {
                return ResourceManager.GetString("FailedToSetRolesForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Existing Person.
        /// </summary>
        public static string FindExistingPersonOption {
            get {
                return ResourceManager.GetString("FindExistingPersonOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Person.
        /// </summary>
        public static string FindPersonTitle {
            get {
                return ResourceManager.GetString("FindPersonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting invitation code....
        /// </summary>
        public static string GettingInvitationCode {
            get {
                return ResourceManager.GetString("GettingInvitationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Afternoon{0}.
        /// </summary>
        public static string GreetingAfternoon {
            get {
                return ResourceManager.GetString("GreetingAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Evening{0}.
        /// </summary>
        public static string GreetingEvening {
            get {
                return ResourceManager.GetString("GreetingEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome{0}.
        /// </summary>
        public static string GreetingGeneric {
            get {
                return ResourceManager.GetString("GreetingGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Morning{0}.
        /// </summary>
        public static string GreetingMorning {
            get {
                return ResourceManager.GetString("GreetingMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient user role..
        /// </summary>
        public static string InsufficientUserRole {
            get {
                return ResourceManager.GetString("InsufficientUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token provided..
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading person details....
        /// </summary>
        public static string LoadingPersonDetails {
            get {
                return ResourceManager.GetString("LoadingPersonDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading system roles....
        /// </summary>
        public static string LoadingSystemRoles {
            get {
                return ResourceManager.GetString("LoadingSystemRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading user details....
        /// </summary>
        public static string LoadingUserDetails {
            get {
                return ResourceManager.GetString("LoadingUserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading user roles....
        /// </summary>
        public static string LoadingUserRoles {
            get {
                return ResourceManager.GetString("LoadingUserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading users....
        /// </summary>
        public static string LoadingUsers {
            get {
                return ResourceManager.GetString("LoadingUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed..
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout failed..
        /// </summary>
        public static string LogoutFailed {
            get {
                return ResourceManager.GetString("LogoutFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now logged out. Thank you for using MartialBase®!.
        /// </summary>
        public static string LogoutSuccessful {
            get {
                return ResourceManager.GetString("LogoutSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage User.
        /// </summary>
        public static string ManageUserTitle {
            get {
                return ResourceManager.GetString("ManageUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting user has no access to requested person..
        /// </summary>
        public static string NoAccessToPerson {
            get {
                return ResourceManager.GetString("NoAccessToPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting user has no associated person..
        /// </summary>
        public static string NoAssociatedPerson {
            get {
                return ResourceManager.GetString("NoAssociatedPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting user has no access to organisation..
        /// </summary>
        public static string NoOrganisationAccess {
            get {
                return ResourceManager.GetString("NoOrganisationAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting user is not admin of organisation..
        /// </summary>
        public static string NotOrganisationAdmin {
            get {
                return ResourceManager.GetString("NotOrganisationAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting user is not a school secretary..
        /// </summary>
        public static string NotSchoolSecretary {
            get {
                return ResourceManager.GetString("NotSchoolSecretary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting user is not a school student..
        /// </summary>
        public static string NotSchoolStudent {
            get {
                return ResourceManager.GetString("NotSchoolStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person cannot become orphan entity..
        /// </summary>
        public static string OrphanPersonEntity {
            get {
                return ResourceManager.GetString("OrphanPersonEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School cannot become orphan entity..
        /// </summary>
        public static string OrphanSchoolEntity {
            get {
                return ResourceManager.GetString("OrphanSchoolEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person &apos;{0}&apos; added to user..
        /// </summary>
        public static string PersonAddedToUser {
            get {
                return ResourceManager.GetString("PersonAddedToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration submitted. Please check your emails for a confirmation link..
        /// </summary>
        public static string RegisterNewUser {
            get {
                return ResourceManager.GetString("RegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register new user..
        /// </summary>
        public static string RegisterNewUserFailed {
            get {
                return ResourceManager.GetString("RegisterNewUserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset failed..
        /// </summary>
        public static string ResetFailed {
            get {
                return ResourceManager.GetString("ResetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to request password reset..
        /// </summary>
        public static string ResetRequestFailed {
            get {
                return ResourceManager.GetString("ResetRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset request sent. Please check your emails for a confirmation link..
        /// </summary>
        public static string ResetRequestSent {
            get {
                return ResourceManager.GetString("ResetRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset successfully! You can now log in using your new credentials..
        /// </summary>
        public static string ResetSuccess {
            get {
                return ResourceManager.GetString("ResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving current user details....
        /// </summary>
        public static string RetrievingCurrentUserDetails {
            get {
                return ResourceManager.GetString("RetrievingCurrentUserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving user roles....
        /// </summary>
        public static string SavingUserRoles {
            get {
                return ResourceManager.GetString("SavingUserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully retrieved invitation code: {0}.
        /// </summary>
        public static string SuccessfullyRetrievedInvitationCode {
            get {
                return ResourceManager.GetString("SuccessfullyRetrievedInvitationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to return to the login page..
        /// </summary>
        public static string ToReturnToLogin {
            get {
                return ResourceManager.GetString("ToReturnToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been locked out, please try again in 10 minutes..
        /// </summary>
        public static string UserLockedOut {
            get {
                return ResourceManager.GetString("UserLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User roles updated successfully..
        /// </summary>
        public static string UserRolesUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UserRolesUpdatedSuccessfully", resourceCulture);
            }
        }
    }
}
